import { useEffect, useState } from 'react';

type View={id?:string;name:string;template:'INFORMATIVE_DASHBOARD'|'NEWS'|'WEATHER'|'KPI'|'KPI_GRID'|'MARKET_TICKER'|'TABLE'|'LIST';refreshSeconds:number;updatedAt:string;stale?:boolean;style:Record<string,string>;data:any};
const fallbackStyle={primaryColor:'#1769b0',accentColor:'#ffad2f',backgroundColor:'#06182b',textColor:'#fff',mutedColor:'#b8cadb',logoUrl:'/somai-logo.png',companyName:'Somai Alimentos'};
function format(value:any,digits=1){const n=Number(value);return Number.isFinite(n)?new Intl.NumberFormat('pt-BR',{maximumFractionDigits:digits}).format(n):String(value??'—')}
function weather(code:any){const value=Number(code);if(value===0)return {icon:'☀',label:'Céu limpo'};if(value<=3)return {icon:'⛅',label:'Parcialmente nublado'};if(value>=51&&value<=67)return {icon:'🌧',label:'Chuva'};if(value>=71&&value<=77)return {icon:'❄',label:'Neve'};if(value>=80&&value<=82)return {icon:'🌦',label:'Pancadas de chuva'};if(value>=95)return {icon:'⛈',label:'Tempestade'};return {icon:'🌤',label:'Condição atual'}}

function InformativeDashboard({view}:{view:View}){
  const data=view.data??{},settings=data.settings??{},modules:string[]=settings.modules??['NEWS','WEATHER','MARKET','DATETIME'];
  const [now,setNow]=useState(new Date()),[newsIndex,setNewsIndex]=useState(0),[marketPage,setMarketPage]=useState(0);
  useEffect(()=>{const timer=window.setInterval(()=>setNow(new Date()),1000);return()=>clearInterval(timer)},[]);
  useEffect(()=>{const length=data.news?.length??0;if(!length)return;const timer=window.setInterval(()=>setNewsIndex(index=>(index+1)%length),Math.max(5,settings.newsRotationSeconds||10)*1000);return()=>clearInterval(timer)},[data.news?.length,settings.newsRotationSeconds]);
  useEffect(()=>{const pages=Math.max(1,Math.ceil((data.market?.length??0)/4));const timer=window.setInterval(()=>setMarketPage(page=>(page+1)%pages),Math.max(5,settings.marketRotationSeconds||10)*1000);return()=>clearInterval(timer)},[data.market?.length,settings.marketRotationSeconds]);
  const article=data.news?.length?data.news[newsIndex%data.news.length]:null,condition=weather(data.weather?.condition),pageItems=(data.market??[]).slice(marketPage*4,marketPage*4+4),tickerItems=data.market??[];
  const card=(module:string)=>{
    if(module==='DATETIME')return <article key={module} className="info-card info-datetime"><p className="info-label">Agora</p><strong>{now.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</strong><span>{now.toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'long'})}</span></article>;
    if(module==='NEWS')return <article key={module} className="info-card info-news" style={article?.image?{backgroundImage:`linear-gradient(90deg,rgba(3,14,27,.98),rgba(3,14,27,.78),rgba(3,14,27,.18)),url(${article.image})`}:undefined}><div><p className="info-label">Últimas notícias</p><h1>{article?.title||'Aguardando notícias atualizadas'}</h1>{article?.description&&<p>{article.description}</p>}{!article&&<p className="info-source-empty">A fonte será consultada novamente de forma automática.</p>}<footer><b>{article?.source||'Notícias'}</b>{article?.publishedAt&&<time>{new Date(article.publishedAt).toLocaleString('pt-BR')}</time>}<span>{data.news?.length?`${newsIndex+1} de ${data.news.length}`:''}</span></footer></div></article>;
    if(module==='WEATHER')return <article key={module} className="info-card info-weather"><p className="info-label">Clima agora</p>{data.weather?<><div className="info-weather-main"><span>{condition.icon}</span><strong>{format(data.weather.temperature,0)}°</strong></div><h2>{data.weather.location||settings.city}</h2><p>{condition.label} · Sensação {format(data.weather.feelsLike,0)}°</p><footer><span>Umidade <b>{format(data.weather.humidity,0)}%</b></span><span>Vento <b>{format(data.weather.wind,0)} km/h</b></span><span>Máx. <b>{format(data.weather.max,0)}°</b> · Mín. <b>{format(data.weather.min,0)}°</b></span></footer></>:<div className="info-source-empty">Clima indisponível agora.<br/>Nova tentativa automática.</div>}</article>;
    return <article key={module} className="info-card info-market"><div className="info-card-title"><div><p className="info-label">Mercado agora</p><h2>Cotações em destaque</h2></div>{pageItems.length>0&&<span>Página {marketPage+1}</span>}</div>{pageItems.length?<div className="info-market-grid">{pageItems.map((item:any)=>{const change=Number(item.change)||0;return <div key={item.symbol}><header>{item.logo&&<img src={item.logo} alt=""/>}<b>{item.symbol}</b></header><strong>{item.currency==='BRL'?'R$ ':''}{format(item.price,2)}</strong><span className={change>0?'positive':change<0?'negative':'neutral'}>{change>0?'▲':change<0?'▼':'—'} {format(Math.abs(change),2)}%</span></div>})}</div>:<div className="info-source-empty">Cotações indisponíveis agora.<br/>Nova tentativa automática.</div>}</article>;
  };
  const speed=settings.tickerSpeed==='FAST'?'38s':settings.tickerSpeed==='SLOW'?'90s':'58s';
  return <section className="info-dashboard" style={{background:view.style.backgroundColor,color:view.style.textColor,'--widget-primary':view.style.primaryColor,'--widget-accent':view.style.accentColor,'--widget-muted':view.style.mutedColor,'--ticker-speed':speed} as React.CSSProperties}><header className="info-top"><img src={view.style.logoUrl||'/somai-logo.png'} onError={event=>{event.currentTarget.src='/somai-logo.png'}}/><div><b>{view.name}</b><span className={view.stale?'stale':''}>{view.stale?'Dados armazenados':'Ao vivo · atualização automática'}</span></div></header><main className={`info-grid info-count-${modules.length}`}>{modules.map(card)}</main>{settings.tickerEnabled&&tickerItems.length>0&&<div className="finance-ticker"><div className="finance-track">{[0,1].map(copy=><div className="finance-group" key={copy}>{tickerItems.map((item:any,index:number)=>{const change=Number(item.change)||0;return <span key={`${copy}-${item.symbol}-${index}`}><b>{item.symbol}</b><strong>{item.currency==='BRL'?'R$ ':''}{format(item.price,2)}</strong><i className={change>0?'positive':change<0?'negative':'neutral'}>{change>0?'▲':change<0?'▼':'—'} {format(Math.abs(change),2)}%</i></span>})}</div>)}</div></div>}<footer className="info-footer"><span>{view.style.companyName}</span><span>{Object.keys(data.errors??{}).length?'Algumas fontes estão temporariamente indisponíveis':'Dados armazenados no servidor para reduzir requisições'}</span><span>Atualizado {new Date(view.updatedAt).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</span></footer></section>;
}

export function DataWidget({url}:{url:string}){
  const key=`widget:${url}`;
  const [view,setView]=useState<View|null>(()=>{try{return JSON.parse(localStorage.getItem(key)??'null')}catch{return null}});
  const [error,setError]=useState('');
  const [newsIndex,setNewsIndex]=useState(0);
  useEffect(()=>{let active=true;let timer:number;const load=async()=>{try{const response=await fetch(url,{cache:'no-store'});const details=await response.json().catch(()=>null);if(!response.ok)throw new Error(Array.isArray(details?.message)?details.message.join(' · '):details?.message||`Erro HTTP ${response.status}`);const value=details as View;if(active){setError('');setView(value);localStorage.setItem(key,JSON.stringify(value));timer=window.setTimeout(load,Math.max(30,value.refreshSeconds||300)*1000)}}catch(cause){if(active)setError((cause as Error).message||'API indisponível');timer=window.setTimeout(load,60000)}};load();return()=>{active=false;clearTimeout(timer)}},[url,key]);
  useEffect(()=>{if(view?.template!=='NEWS'||!view.data?.items?.length)return;const timer=window.setInterval(()=>setNewsIndex(index=>(index+1)%view.data.items.length),9000);return()=>clearInterval(timer)},[view?.template,view?.data?.items?.length]);
  if(!view)return <div className="dynamic-error"><img src="/somai-logo.png"/><span className="dynamic-error-label">Widget de dados</span><strong>{error?'Não foi possível carregar':'Preparando painel de dados…'}</strong><p>{error||'Consultando a API e preparando o conteúdo.'}</p><small>{error?'Confira também os logs da API. Nova tentativa em 60 segundos.':'O último conteúdo ficará disponível mesmo sem conexão.'}</small></div>;
  const s={...fallbackStyle,...view.style},d=view.data,condition=weather(d?.condition);
  const article=view.template==='NEWS'&&d.items?.length?d.items[newsIndex%d.items.length]:null;
  if(view.template==='INFORMATIVE_DASHBOARD')return <InformativeDashboard view={{...view,style:s}}/>;
  return <section className="widget" style={{background:s.backgroundColor,color:s.textColor,'--widget-primary':s.primaryColor,'--widget-accent':s.accentColor,'--widget-muted':s.mutedColor} as React.CSSProperties}>
    <div className="widget-stripe"/><header className="widget-header"><img src={s.logoUrl||'/somai-logo.png'} onError={event=>{event.currentTarget.src='/somai-logo.png'}}/><span className={view.stale?'widget-pill stale':'widget-pill'}>{view.stale?'Exibindo dados armazenados':'Atualização automática'}</span></header>
    {view.template==='NEWS'&&<main className="auto-news" style={article?.image?{backgroundImage:`linear-gradient(90deg,rgba(2,6,23,.98) 0%,rgba(2,6,23,.86) 48%,rgba(2,6,23,.12) 100%),url(${article.image})`}:undefined}><div className="auto-news-copy"><div className="auto-news-meta"><span>{article?.source||d.title||'Notícias'}</span>{article?.publishedAt&&<time>{new Date(article.publishedAt).toLocaleString('pt-BR')}</time>}</div><h1>{article?.title||'Aguardando notícias'}</h1>{article?.description&&<p>{article.description}</p>}<div className="auto-news-progress"><i style={{width:`${((newsIndex%d.items.length)+1)/d.items.length*100}%`}}/></div><small>{(newsIndex%d.items.length)+1} de {d.items.length}</small></div></main>}
    {view.template==='WEATHER'&&<main className="weather-layout"><div className="weather-current"><p className="widget-eyebrow">{d.location}</p><div className="weather-value"><span>{condition.icon}</span>{format(d.temperature)}°</div><h1>{condition.label}</h1><p className="widget-muted">Sensação de {format(d.feelsLike)}°</p><div className="weather-details"><span><b>{format(d.humidity,0)}%</b> Umidade</span><span><b>{format(d.wind)}</b> km/h de vento</span></div></div><div className="forecast-grid">{d.forecast?.slice(0,7).map((day:any,index:number)=><article key={index}><p>{day.date?new Date(`${day.date}T12:00:00`).toLocaleDateString('pt-BR',{weekday:'short',day:'2-digit'}):'—'}</p><span>{index===0?condition.icon:'🌤'}</span><strong>{format(day.max,0)}°</strong><small>{format(day.min,0)}° · chuva {format(day.rain,0)}%</small></article>)}</div></main>}
    {view.template==='KPI'&&<main className="kpi-layout"><p className="widget-eyebrow">Indicador atualizado</p><h1>{d.label||view.name}</h1><div className="kpi-value">{format(d.value)}<small>{d.suffix}</small></div>{d.trend!==undefined&&d.trend!==''&&<p className={Number(d.trend)>=0?'trend positive':'trend negative'}>{Number(d.trend)>=0?'▲':'▼'} {format(Math.abs(Number(d.trend)),2)}%</p>}<p className="widget-muted">{d.subtitle||d.updatedAt&&`Referência: ${d.updatedAt}`}</p></main>}
    {view.template==='MARKET_TICKER'&&<main className="market-layout"><div><p className="widget-eyebrow">Cotações</p><h1>{d.title}</h1></div><div className="market-grid">{d.items?.slice(0,8).map((item:any,index:number)=>{const positive=Number(item.change)>=0;return <article key={index}><div className="market-name">{item.logo&&<img src={item.logo}/>}<div><strong>{item.symbol}</strong><small>{item.name}</small></div></div><p>R$ {format(item.price,2)}</p><span className={positive?'positive':'negative'}>{positive?'▲':'▼'} {format(Math.abs(Number(item.change)),2)}%</span></article>})}</div></main>}
    {view.template==='KPI_GRID'&&<main className="grid-layout"><div><p className="widget-eyebrow">Visão geral</p><h1>{d.title}</h1></div><div className="kpi-grid">{d.items?.slice(0,8).map((item:any,index:number)=>{const hasTarget=item.target!==undefined&&item.target!==null&&item.target!=='';const ratio=hasTarget?Math.min(100,Math.max(0,Number(item.value)/Number(item.target)*100)):100;return <article key={index}><p>{item.label}</p><strong>{format(item.value)} <small>{item.unit}</small></strong>{hasTarget&&<><div className="progress"><i style={{width:`${ratio}%`}}/></div><span>Meta {format(item.target)} · {format(ratio,0)}%</span></>}</article>})}</div></main>}
    {view.template==='TABLE'&&<main className="table-layout"><div><p className="widget-eyebrow">Dados consolidados</p><h1>{d.title}</h1></div><table><thead><tr>{d.columns?.map((column:any)=><th key={column.key}>{column.label}</th>)}</tr></thead><tbody>{d.rows?.slice(0,10).map((row:any,index:number)=><tr key={index}>{d.columns?.map((column:any)=><td key={column.key}>{format(row[column.key])}</td>)}</tr>)}</tbody></table></main>}
    {view.template==='LIST'&&<main className="list-layout"><div><p className="widget-eyebrow">Informações</p><h1>{d.title}</h1></div><div className="list-items">{d.items?.slice(0,7).map((item:any,index:number)=><article key={index}><i>{String(index+1).padStart(2,'0')}</i><div><strong>{item.title}</strong>{item.description&&<p>{item.description}</p>}</div>{item.value!==undefined&&<span>{format(item.value)}</span>}</article>)}</div></main>}
    <footer className="widget-footer"><span>{s.companyName}</span><span>Atualizado em {new Date(view.updatedAt).toLocaleString('pt-BR')}</span></footer>
  </section>;
}
