import { FormEvent, useEffect, useState } from 'react';
import { Cloud, Monitor, Radio, ShieldCheck } from 'lucide-react';
import { API_URL, api } from '../lib/api';
import { Button, Card, Input } from '../components/ui';

export function Login(){
  const [error,setError]=useState(''),[busy,setBusy]=useState(false),[health,setHealth]=useState<'checking'|'online'|'offline'>('checking');
  useEffect(()=>{api<{status:string}>('/health').then(()=>setHealth('online')).catch(()=>setHealth('offline'))},[]);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setError('');setBusy(true);const form=new FormData(event.currentTarget);try{const result=await api<{accessToken:string;user:{id:string;name:string;email:string;role:string}}>('/auth/login',{method:'POST',body:JSON.stringify({email:form.get('email'),password:form.get('password')})});localStorage.setItem('accessToken',result.accessToken);localStorage.setItem('currentUser',JSON.stringify(result.user));location.href='/'}catch(event){setError((event as Error).message)}finally{setBusy(false)}}
  return <main className="login-shell"><section className="login-brand"><div className="login-logo"><span><img src="/somai-logo.png" alt="SOMAI"/></span><div><strong>Signal Signage</strong><small>Central corporativa SOMAI</small></div></div><div className="login-hero"><span className="login-kicker"><i/>Infraestrutura conectada</span><h1>Comunicação que <em>move a operação.</em></h1><p>Controle telas, conteúdos e programações a partir de uma central tecnológica, segura e preparada para funcionar continuamente.</p></div><div className="login-features"><div><Monitor size={18}/><strong>Gestão central</strong><small>Todas as TVs em um painel</small></div><div><Cloud size={18}/><strong>Acesso seguro</strong><small>Cloudflare Tunnel e HTTPS</small></div><div><ShieldCheck size={18}/><strong>Operação resiliente</strong><small>Cache local e sincronização</small></div></div></section><section className="login-form-side"><Card className="login-card"><div className="login-card-heading"><span>Portal administrativo</span><h2>Bem-vindo de volta</h2><p>Entre com suas credenciais para acessar o centro de comando.</p></div><div className={`api-health ${health}`}><i/><div><strong>{health==='online'?'API conectada':health==='offline'?'API indisponível':'Verificando servidor...'}</strong><small>{API_URL}</small></div></div><form onSubmit={submit} className="space-y-4"><label className="login-label">E-mail corporativo<Input name="email" type="email" placeholder="nome@empresa.com.br" required/></label><label className="login-label">Senha<Input name="password" type="password" placeholder="Digite sua senha" required/></label>{error&&<p className="notice notice-error">{error}</p>}<Button className="w-full" disabled={busy}><Radio size={16}/>{busy?'Conectando...':'Entrar no painel'}</Button></form><p className="login-footnote">Acesso protegido · Signal Signage SOMAI</p></Card></section></main>;
}
